// FORWARD COMPILER SECTION
#include <not_python.h>
PYSTRING NOT_PYTHON_STRING_CONSTANTS[] = {
};

// STRUCT DECLARATIONS COMPILER SECTION

// VARIABLE DECLARATIONS COMPILER SECTION
PYINT x;
PYINT y;
PYINT z;

// FUNCTION DECLARATIONS COMPILER SECTION

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
PYINT NP_var0 = 1+2;
x = NP_var0+3;
PYINT NP_var1 = 9-8;
y = NP_var1-7;
PYINT NP_var2 = 2*x;
PYINT NP_var3 = 3*y;
z = NP_var2+NP_var3;
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0