// FORWARD COMPILER SECTION
#include <not_python.h>
PYSTRING NOT_PYTHON_STRING_CONSTANTS[] = {
};

// STRUCT DECLARATIONS COMPILER SECTION

// VARIABLE DECLARATIONS COMPILER SECTION
PYINT z;

// FUNCTION DECLARATIONS COMPILER SECTION
PYINT my_function(PYINT x, PYINT y);

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
PYINT NP_var2 = 1+2;
PYINT NP_var0 = NP_var2+3;
PYINT NP_var3 = 4*5;
PYINT NP_var1 = NP_var3*6;
z = my_function(NP_var0, NP_var1);
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0