// FORWARD COMPILER SECTION
#include <not_python.h>
PYSTRING NOT_PYTHON_STRING_CONSTANTS[] = {
{.data="Hello,", .length=6},
{.data=" World.", .length=7}};

// STRUCT DECLARATIONS COMPILER SECTION

// VARIABLE DECLARATIONS COMPILER SECTION
PYSTRING a;
PYSTRING b;
PYSTRING c;

// FUNCTION DECLARATIONS COMPILER SECTION

// FUNCTION DEFINITIONS COMPILER SECTION

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
a = NOT_PYTHON_STRING_CONSTANTS[0];
b = NOT_PYTHON_STRING_CONSTANTS[1];
c = str_add(a, b);
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0