// FORWARD COMPILER SECTION
#include <not_python.h>
PYSTRING NOT_PYTHON_STRING_CONSTANTS[] = {
};

// STRUCT DECLARATIONS COMPILER SECTION

// VARIABLE DECLARATIONS COMPILER SECTION
PYFLOAT simple_expression4_a;

// FUNCTION DECLARATIONS COMPILER SECTION

// FUNCTION DEFINITIONS COMPILER SECTION

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
PYINT NP_var1 = 2*3;
PYINT NP_var0 = 1+NP_var1;
PYINT NP_var3 = 3*2;
PYFLOAT NP_var2 = (PYFLOAT)NP_var3/(PYFLOAT)4;
simple_expression4_a = NP_var0-NP_var2;
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0