// FORWARD COMPILER SECTION
#include <not_python.h>
NpString NOT_PYTHON_STRING_CONSTANTS[] = {
};

// STRUCT DECLARATIONS COMPILER SECTION

// VARIABLE DECLARATIONS COMPILER SECTION

// FUNCTION DECLARATIONS COMPILER SECTION
NpFloat function_function(NpInt x, NpInt y);

// FUNCTION DEFINITIONS COMPILER SECTION
NpFloat function_function(NpInt x, NpInt y) {
}

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0