// FORWARD COMPILER SECTION
#include <not_python.h>
PyString NOT_PYTHON_STRING_CONSTANTS[] = {
};

// STRUCT DECLARATIONS COMPILER SECTION

// VARIABLE DECLARATIONS COMPILER SECTION

// FUNCTION DECLARATIONS COMPILER SECTION
PyFloat function_function(PyInt x, PyInt y);

// FUNCTION DEFINITIONS COMPILER SECTION
PyFloat function_function(PyInt x, PyInt y) {
}

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0