// FORWARD COMPILER SECTION
#include <not_python.h>
PYSTRING NOT_PYTHON_STRING_CONSTANTS[] = {
};

// STRUCT DECLARATIONS COMPILER SECTION

// VARIABLE DECLARATIONS COMPILER SECTION
PYLIST list_index_l;
PYINT list_index_i;

// FUNCTION DECLARATIONS COMPILER SECTION

// FUNCTION DEFINITIONS COMPILER SECTION

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
PYINT NP_var0 = 1;
list_index_l = LIST_INIT(PYINT);
LIST_APPEND(list_index_l, PYINT, NP_var0);
PYLIST NP_var2 = list_index_l;
PYINT NP_var3 = 1;
LIST_INDEX(NP_var2, PYINT, int_eq, NP_var3, list_index_i);
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0