// FORWARD COMPILER SECTION
#include <not_python.h>
PYSTRING NOT_PYTHON_STRING_CONSTANTS[] = {
};

// STRUCT DECLARATIONS COMPILER SECTION

// VARIABLE DECLARATIONS COMPILER SECTION
PYINT NP_var1;
PYLIST NP_var0;
PYINT NP_var3;
PYLIST NP_var2;
PYLIST list_addition_l;

// FUNCTION DECLARATIONS COMPILER SECTION

// FUNCTION DEFINITIONS COMPILER SECTION

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
NP_var1 = 1;
NP_var0 = LIST_INIT(PYINT);
LIST_APPEND(NP_var0, PYINT, NP_var1);
NP_var1 = 2;
LIST_APPEND(NP_var0, PYINT, NP_var1);
NP_var1 = 3;
LIST_APPEND(NP_var0, PYINT, NP_var1);
NP_var3 = 4;
NP_var2 = LIST_INIT(PYINT);
LIST_APPEND(NP_var2, PYINT, NP_var3);
NP_var3 = 5;
LIST_APPEND(NP_var2, PYINT, NP_var3);
NP_var3 = 6;
LIST_APPEND(NP_var2, PYINT, NP_var3);
list_addition_l = list_add(NP_var0, NP_var2);
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0