// FORWARD COMPILER SECTION
#include <not_python.h>
PYSTRING NOT_PYTHON_STRING_CONSTANTS[] = {
{.data="ten", .length=3},
{.data="twenty", .length=6}};

// STRUCT DECLARATIONS COMPILER SECTION

// VARIABLE DECLARATIONS COMPILER SECTION
PYDICT dict_set_item_d;

// FUNCTION DECLARATIONS COMPILER SECTION

// FUNCTION DEFINITIONS COMPILER SECTION

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
dict_set_item_d = DICT_INIT(PYINT, PYSTRING, void_int_eq);
PYDICT NP_var0 = dict_set_item_d;
PYSTRING NP_var1 = NOT_PYTHON_STRING_CONSTANTS[0];
PYINT NP_var2 = 10;
PYSTRING NP_var3 = NOT_PYTHON_STRING_CONSTANTS[0];
dict_set_item(NP_var0, &NP_var2, &NP_var3);
PYDICT NP_var4 = dict_set_item_d;
PYSTRING NP_var5 = NOT_PYTHON_STRING_CONSTANTS[1];
PYINT NP_var6 = 20;
PYSTRING NP_var7 = NOT_PYTHON_STRING_CONSTANTS[1];
dict_set_item(NP_var4, &NP_var6, &NP_var7);
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0