// FORWARD COMPILER SECTION
#include <not_python.h>
NpString NOT_PYTHON_STRING_CONSTANTS[] = {
};

// STRUCT DECLARATIONS COMPILER SECTION
typedef struct {NpFloat x;NpFloat y;NpFloat z;} class_Vec3;

// VARIABLE DECLARATIONS COMPILER SECTION

// FUNCTION DECLARATIONS COMPILER SECTION

// FUNCTION DEFINITIONS COMPILER SECTION

// INIT MODULE FUNCTION COMPILER SECTION
static void init_module(void) {
}

// MAIN FUNCTION COMPILER SECTION
int main(void) {
init_module();
}
exitcode=0