/*
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
this code is generated by `scripts/codegen.py` and should not be edited manually
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/
#ifndef GENERATED_H
#define GENERATED_H

#include <stdbool.h>
#include <stddef.h>

typedef enum {
    NOT_A_KEYWORD = 0,
    KW_AND = 17,
    KW_AS = 67,
    KW_ASSERT = 78,
    KW_BREAK = 82,
    KW_CLASS = 99,
    KW_CONTINUE = 144,
    KW_DEF = 13,
    KW_DEL = 19,
    KW_ELIF = 126,
    KW_ELSE = 135,
    KW_EXCEPT = 69,
    KW_FINALLY = 26,
    KW_FOR = 37,
    KW_FROM = 1,
    KW_GLOBAL = 45,
    KW_IF = 62,
    KW_IMPORT = 87,
    KW_IN = 70,
    KW_IS = 75,
    KW_LAMBDA = 29,
    KW_NONLOCAL = 129,
    KW_NOT = 47,
    KW_OR = 80,
    KW_PASS = 4,
    KW_RAISE = 97,
    KW_RETURN = 92,
    KW_TRY = 61,
    KW_WHILE = 102,
    KW_WITH = 9,
    KW_YIELD = 100,
} Keyword;

#define KEYWORDS_MAX 145
size_t kw_hash(char* kw);
Keyword is_keyword(char* word);
const char* kw_to_cstr(Keyword kw);

typedef enum {
    OPERATOR_PLUS = 86,
    OPERATOR_MINUS = 90,
    OPERATOR_MULT = 84,
    OPERATOR_DIV = 94,
    OPERATOR_MOD = 74,
    OPERATOR_POW = 126,
    OPERATOR_FLOORDIV = 5,
    OPERATOR_ASSIGNMENT = 122,
    OPERATOR_PLUS_ASSIGNMENT = 11,
    OPERATOR_MINUS_ASSIGNMENT = 15,
    OPERATOR_MULT_ASSIGNMENT = 9,
    OPERATOR_DIV_ASSIGNMENT = 19,
    OPERATOR_MOD_ASSIGNMENT = 135,
    OPERATOR_FLOORDIV_ASSIGNMENT = 66,
    OPERATOR_POW_ASSIGNMENT = 51,
    OPERATOR_AND_ASSIGNMENT = 1,
    OPERATOR_OR_ASSIGNMENT = 37,
    OPERATOR_XOR_ASSIGNMENT = 113,
    OPERATOR_RSHIFT_ASSIGNMENT = 111,
    OPERATOR_LSHIFT_ASSIGNMENT = 105,
    OPERATOR_EQUAL = 47,
    OPERATOR_NOT_EQUAL = 127,
    OPERATOR_GREATER = 124,
    OPERATOR_LESS = 120,
    OPERATOR_GREATER_EQUAL = 49,
    OPERATOR_LESS_EQUAL = 45,
    OPERATOR_BITWISE_AND = 76,
    OPERATOR_BITWISE_OR = 112,
    OPERATOR_BITWISE_XOR = 52,
    OPERATOR_BITWISE_NOT = 116,
    OPERATOR_CONDITIONAL_IF = 40,
    OPERATOR_CONDITIONAL_ELSE = 118,
    OPERATOR_LSHIFT = 44,
    OPERATOR_RSHIFT = 50,
    OPERATOR_CALL = 71,
    OPERATOR_GET_ITEM = 2,
    OPERATOR_GET_ATTR = 14,
    OPERATOR_LOGICAL_AND = 132,
    OPERATOR_LOGICAL_OR = 64,
    OPERATOR_LOGICAL_NOT = 39,
} Operator;

#define OPERATORS_MAX 136
#define MAX_PRECEDENCE 16
extern const unsigned int PRECEDENCE_TABLE[OPERATORS_MAX];
extern const bool IS_ASSIGNMENT_OP[OPERATORS_MAX];
Operator op_from_cstr(char* op);
const char* op_to_cstr(Operator op);

#endif