#ifndef OPERATORS_H
#define OPERATORS_H

#include <stdbool.h>

typedef enum {
    OPERATOR_PLUS = 16,
    OPERATOR_MINUS = 20,
    OPERATOR_MULT = 14,
    OPERATOR_DIV = 24,
    OPERATOR_MOD = 4,
    OPERATOR_POW = 56,
    OPERATOR_FLOORDIV = 1,
    OPERATOR_ASSIGNMENT = 52,
    OPERATOR_PLUS_ASSIGNMENT = 7,
    OPERATOR_MINUS_ASSIGNMENT = 11,
    OPERATOR_MULT_ASSIGNMENT = 5,
    OPERATOR_DIV_ASSIGNMENT = 15,
    OPERATOR_MOD_ASSIGNMENT = 65,
    OPERATOR_FLOORDIV_ASSIGNMENT = 62,
    OPERATOR_POW_ASSIGNMENT = 47,
    OPERATOR_AND_ASSIGNMENT = 67,
    OPERATOR_OR_ASSIGNMENT = 29,
    OPERATOR_XOR_ASSIGNMENT = 39,
    OPERATOR_RSHIFT_ASSIGNMENT = 37,
    OPERATOR_LSHIFT_ASSIGNMENT = 31,
    OPERATOR_EQUAL = 43,
    OPERATOR_NOT_EQUAL = 57,
    OPERATOR_GREATER = 54,
    OPERATOR_LESS = 50,
    OPERATOR_GREATER_EQUAL = 45,
    OPERATOR_LESS_EQUAL = 41,
    OPERATOR_BITWISE_AND = 6,
    OPERATOR_BITWISE_OR = 38,
    OPERATOR_BITWISE_XOR = 48,
    OPERATOR_BITWISE_NOT = 42,
    OPERATOR_LSHIFT = 40,
    OPERATOR_RSHIFT = 46,
} Operator;

extern const bool IS_ASSIGNMENT_OP[70];
Operator op_from_cstr(char* op);

#endif
